version: '3.8'

services:
  iportfolio:
    build: .
    ports:
      - "3020:5173" # Host:Container
    volumes:
      - .:/app
      - /app/node_modules # Prevents local node_modules override
    container_name: iportfolio_container

volumes:
  vite-serv:
